{% set name = "defcon" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/defcon-{{ version }}.zip
  sha256: aee396e6d69e45ae65c8264781392d4c29116934b2737ad76d8230b40c182a44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - fonttools >=4.10.0
    - python >=3.7
    - fs

test:
  imports:
    - defcon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotools/defcon
  summary: A set of flexible objects for representing UFO data.
  license: MIT
  license_file:
    - License.txt

extra:
  recipe-maintainers:
    - jan-janssen
