{% set name = "defcon" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25dfe7fd0152ccf292cb190d1928a47d588899c20b046854293e039e1c93e5e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - fonttools >=4.59.0
    - python >={{ python_min }}
    - fs

test:
  imports:
    - defcon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robotools/defcon
  summary: A set of flexible objects for representing UFO data.
  license: MIT
  license_file:
    - License.txt

extra:
  recipe-maintainers:
    - jan-janssen
