{% set name = "defcon" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/defcon-{{ version }}.zip
  sha256: aca8674a8f71723af6a08f332f3ed3156ba0fe00591eb5aff7572caad1472d09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - fonttools >=4.10.0
    - python >={{ python_min }}
    - fs

test:
  imports:
    - defcon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robotools/defcon
  summary: A set of flexible objects for representing UFO data.
  license: MIT
  license_file:
    - License.txt

extra:
  recipe-maintainers:
    - jan-janssen
