{% set name = "defcon" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/defcon-{{ version }}.zip
  sha256: 56de26d7c75f164eea03e28bc11b4c769c68d705fa186dfcaeb56c27f9a4cc0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - fonttools >=4.10.0
    - python >={{ python_min }}
    - fs

test:
  imports:
    - defcon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robotools/defcon
  summary: A set of flexible objects for representing UFO data.
  license: MIT
  license_file:
    - License.txt

extra:
  recipe-maintainers:
    - jan-janssen
